### ISSUE TITLE
User name in PR showing up above text baseline in Firefox on Linux

### ISSUE THREAD

**Issue by dmarti** [zombie/blind-reviews#24] opened 2018-01-10 18:12 UTC
![screenshot from 2018-01-10 10-11-34](https://user-images.githubusercontent.com/48007/34788224-bdd558fa-f5ee-11e7-896f-8b1627ab6b38.png)

Recent PR has the blind-reviews icon but username visible.

**Comment by zombie** [comment] 2018-01-23 00:00
This is on purpose, user's own PRs are not redacted by default, see Issue #16 (and the icon is our only UI, so it is always visible, whether blinded or not).

Though I notice that your username text is not properly aligned vertically, and I wanna fix that.  It looks fine in Firefox on Windows, so it must be cross-platform css differences.

I'm presuming that's Firefox on Linux?

**Comment by dmarti** [comment] 2018-01-23 00:51
Yes, it's Firefox on Linux -- Nightly (Firefox 59)

**Comment by freaktechnik** [comment] 2018-03-09 21:48
This is on Nightly on elementary OS without WebRender or accelerated graphics and Refined Github installed.

Without:
![image](https://user-images.githubusercontent.com/640949/37231562-e4620f2e-23eb-11e8-8694-97c13ef8e16e.png)

With:
![image](https://user-images.githubusercontent.com/640949/37231601-06739880-23ec-11e8-974c-e4c283f8b657.png)

**Comment by zombie** [comment] 2018-03-09 22:32
Yeah, I can't exactly reproduce this either.  I tried on two different Linux installs, one looks as expected (like @freaktechnik's screenshots above), and the other shows author's username slightly elevated from the baseline, both with and without the extension enabled (seems to depend on screen resolution and text zoom level).

![with png](https://user-images.githubusercontent.com/207002/37232381-146b0c5e-23ef-11e8-8694-920257d38234.png)
![without png](https://user-images.githubusercontent.com/207002/37232382-148e9dae-23ef-11e8-9a00-e9f555283c6f.png)

Closing this, since it seems to be a github css and/or Linux fonts issue, and I don't think there much we can do here.

**Closed by zombie** 2018-03-09 22:32 UTC
